# tagline: 
# description: 
# url: https://

author: 
social:
  name: 
  links: 
    - https://
    - https://

# google_site_verification: a

lang: pt_BR

permalink: /blog/post/:title:output_ext

paginate: 5
paginate_path: /blog/page/:num/

sass:
  load_paths: 
    - _sass/bootstrap
    - _sass
  style: compressed

plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-redirect-from
  - jekyll-seo-tag