# tagline: 
# description: 
# url: https://
# google_site_verification: a

name: SER
author: 

lang: pt_BR

permalink: /blog/post/:title:output_ext

paginate: 5
paginate_path: /blog/page/:num/

sass:
  sass_dir: _sass
  style: compressed

plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-redirect-from
  - jekyll-seo-tag